FROM osuosl/ubuntu-ppc64le-cuda:9.2-cudnn7

ARG user=pytorch
ARG group=pytorch
ARG uid=1001
ARG gid=1001
ARG PYTORCH_AGENT_HOME=/home/${user}

#ARG user=jenkins
#ARG group=jenkins
#ARG uid=1000
#ARG gid=1000
#ARG JENKINS_AGENT_HOME=/home/${user}

#ENV JENKINS_AGENT_HOME ${JENKINS_AGENT_HOME}
ENV PYTORCH_AGENT_HOME ${PYTORCH_AGENT_HOME}
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV PATH $PATH:$JAVA_HOME/bin
ENV PYTHON_VERSION ${variable:-3}
ENV BUILD_ONLY ${variable:-NO}

RUN groupadd -g ${gid} ${group} && \
    useradd -d "${PYTORCH_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# setup sudo
RUN apt-get update && \
    apt-get install --no-install-recommends -y sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install conda py3
RUN curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-ppc64le.sh \
    -o ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p /opt/miniconda && \
    export PATH=/opt/miniconda/bin:$PATH && \
    conda install -y pyyaml typing cffi && \
    pip install numpy scipy==1.0.0 && \
    conda clean -ya

#USER jenkins
#RUN export PATH=$JENKINS_AGENT_HOME/miniconda/bin:$PATH && \
#    conda install -y pyyaml typing cffi cmake && \
#    pip install numpy scipy==1.0.0 

# Install conda py2
RUN export PATH=/opt/miniconda/bin:$PATH && \
    conda create -n py2k python=2 -y && \
    bash -c "source activate py2k" && \
    export CONDA_ROOT_PREFIX="/opt/miniconda/envs/py2k" && \
    conda install -y pyyaml typing cffi && \
    ${CONDA_ROOT_PREFIX}/bin/pip install numpy scipy==1.0.0 && \
    conda clean -ya

#RUN export PATH=${JENKINS_AGENT_HOME}/miniconda/bin:$PATH && \
#    bash -c "source activate py2k" && \
#    export CONDA_ROOT_PREFIX="$JENKINS_AGENT_HOME/miniconda/envs/py2k" && \
#    conda install -y pyyaml typing cffi cmake && \
#    ${CONDA_ROOT_PREFIX}/bin/pip install numpy scipy==1.0.0

COPY build.sh ./
COPY build_mpi.92.sh ./
COPY build_nimbix.sh ./ 
COPY build_nimbix_with_scipy_92.sh ./
COPY build_nimbix_with_scipy.sh ./
COPY refresh_image_with_mpi.92.sh ./
RUN pwd
RUN ls -l
RUN ./refresh_image_with_mpi.92.sh pytorch HEAD master foo ${PYTHON_VERSION} LINUX


ENTRYPOINT ["./build_mpi.92.sh"]
