FROM osuosl/ubuntu-ppc64le-cuda:9.0-cudnn7

#RUN git clone https://github.com/avmgithub/pytorch_builder.git
COPY build.sh ./
COPY build_nimbix.sh ./
COPY refresh_image_with_mpi.sh ./
RUN pwd
RUN ls
RUN ./refresh_image_with_mpi.sh pytorch HEAD master foo 3 LINUX


ENTRYPOINT ["./build.sh"]
