FROM osuosl/ubuntu-ppc64le-cuda:DOCKER_VERSION

ARG user=pytorch
ARG group=pytorch
ARG uid=1001
ARG gid=1001
ARG PYTORCH_AGENT_HOME=/home/${user}

ENV PYTORCH_AGENT_HOME ${PYTORCH_AGENT_HOME}
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV PATH $PATH:$JAVA_HOME/bin
ENV PYTHON_VERSION ${variable:-3}
ENV BUILD_ONLY ${variable:-NO}
ENV CREATE_ARTIFACTS ${variable:-NO}

RUN groupadd -g ${gid} ${group} && \
    useradd -d "${PYTORCH_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}" && \
    groupmod -g 10000 jenkins && \
    usermod -g 10000 -u 10000 jenkins

# setup sudo
RUN apt-get update && \
    apt-get install --no-install-recommends -y sudo libopenblas-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install conda py3
RUN curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-ppc64le.sh \
    -o ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p /opt/miniconda && \
    export PATH=/opt/miniconda/bin:$PATH && \
    conda install -y pyyaml typing cffi pillow hypothesis cmake ninja && \
    pip install --upgrade pip && \
    pip install numpy psutil && \
    conda clean -ya

# Install conda py2
RUN export PATH=/opt/miniconda/bin:$PATH && \
    conda create -n py2k python=2 -y && \
    bash -c "source activate py2k" && \
    export CONDA_ROOT_PREFIX="/opt/miniconda/envs/py2k" && \
    conda install -y pyyaml typing cffi pillow hypothesis cmake ninja && \
    pip install --upgrade pip && \
    ${CONDA_ROOT_PREFIX}/bin/pip install numpy psutil && \
    conda clean -ya

COPY build_mpi.sh ./
COPY build_nimbix_with_scipy.sh ./
COPY refresh_image_with_mpi.sh ./
COPY buildme.mpi ./
RUN pwd
RUN ls
RUN ./buildme.mpi
RUN ./refresh_image_with_mpi.sh pytorch HEAD master foo ${PYTHON_VERSION} LINUX


#ENTRYPOINT ["./build_mpi.sh"]
